# Google OAuth 2.0
spring.security.oauth2.client.registration.google.client-id=747513435467-24psjd2morjgiendif3qq3dicqvq5t4s.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email,profile
# Github OAuth 2.0
spring.security.oauth2.client.registration.github.client-id=Iv23ctveottM1SpUC04f
spring.security.oauth2.client.registration.github.client-secret=14ec8721e3d2f599b1c23864519bca99d847469f
spring.security.oauth2.client.registration.github.scope=email,profile
# cloudinary configurations
cloudinary.api.key=116457625249221
cloudinary.api.secret=jH5Kyn-2_pdjUHu8j4hBokBVnXM
cloudinary.cloud.name=dnfk0pvir
#Email configurations
spring.mail.host= smtp.gmail.com
spring.mail.port=587
spring.mail.username=26asmi2004@gmail.com
spring.mail.password=zsew kbbw okrk kvhb
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
#spring.mail.properties.domain_name=scm@demomailtrap.com

gemini.api.key=AIzaSyCerFciT9It0LxmcGsys46WI_i0v6hhljY

spring.mail.properties.mail.debug=true
logging.level.org.springframework.mail=DEBUG
logging.level.org.springframework.boot.autoconfigure.mail=DEBUG
