# Google OAuth 2.0
spring.security.oauth2.client.registration.google.client-id=550994776114-50as64062lreorkcvu6vf01qe7olcim0.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email,profile
# Github OAuth 2.0
spring.security.oauth2.client.registration.github.client-id=Iv23ctveottM1SpUC04f
spring.security.oauth2.client.registration.github.client-secret=31363087fe2348c49e96266ffd8822df38b5df43
spring.security.oauth2.client.registration.github.scope=email,profile
# cloudinary configurations
cloudinary.api.key=898946826379514
cloudinary.api.secret=39JteZMzReWVny-j0-74eTenXlU
cloudinary.cloud.name=dnfk0pvir
#Email configurations
spring.mail.host= smtp.gmail.com
spring.mail.port=587
spring.mail.username=26asmi2004@gmail.com
spring.mail.password=kulu bruv xulh mcar
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
#spring.mail.properties.domain_name=scm@demomailtrap.com

spring.mail.properties.mail.debug=true
logging.level.org.springframework.mail=DEBUG
logging.level.org.springframework.boot.autoconfigure.mail=DEBUG