# Google OAuth 2.0
spring.security.oauth2.client.registration.google.client-id=
spring.security.oauth2.client.registration.google.client-secret=
spring.security.oauth2.client.registration.google.scope=email,profile
# Github OAuth 2.0
spring.security.oauth2.client.registration.github.client-id=
spring.security.oauth2.client.registration.github.client-secret=
spring.security.oauth2.client.registration.github.scope=email,profile
# cloudinary configurations
cloudinary.api.key=
cloudinary.api.secret=
cloudinary.cloud.name=dnfk0pvir
#Email configurations
spring.mail.host= smtp.gmail.com
spring.mail.port=587
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
#spring.mail.properties.domain_name=scm@demomailtrap.com

spring.mail.properties.mail.debug=true
logging.level.org.springframework.mail=DEBUG
logging.level.org.springframework.boot.autoconfigure.mail=DEBUG
